apiVersion: v2
name: versitygw
type: application
description: Helm chart for Versity S3 gateway to a Posix backend
home: https://github.com/RobSlgm/versitygw
icon: https://github.com/versity/versitygw/raw/assets/assets/logo.svg
sources: 
  - https://github.com/RobSlgm/versitygw
  - https://github.com/versity/versitygw
keywords:
  - versitygw
  - self-hosted
  - s3

version: 1.3.1
appVersion: "v1.3.1"
