apiVersion: v2
name: versitygw
type: application
description: Helm chart for Versity S3 gateway
home: https://github.com/versity/versitygw
icon: https://github.com/versity/versitygw/raw/assets/assets/logo.svg
keywords:
  - versitygw
  - self-hosted
  - s3

version: 1.0.19
appVersion: "v1.0.20"
