apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "versitygw.fullname" . }}
  labels:
    {{- include "versitygw.labels" . | nindent 4 }}
spec:
  strategy:
    type: Recreate
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "versitygw.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "versitygw.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "versitygw.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["posix", "/mnt/data"]
          env:
            - name: ROOT_ACCESS_KEY_ID 
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.versitygw.admin.s3Credentials.accessKeyId.name }}
                  key: {{ .Values.versitygw.admin.s3Credentials.accessKeyId.key }}
            - name: ROOT_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.versitygw.admin.s3Credentials.secretAccessKey.name }}
                  key: {{ .Values.versitygw.admin.s3Credentials.secretAccessKey.key }}
            {{- if .Values.persistence.versioning.enabled }}
            - name: VGW_VERSIONING_DIR
              value: /mnt/versioning
            {{- end }}
            {{- if .Values.persistence.iam.enabled }}
            - name: VGW_IAM_DIR
              value: /mnt/iam
            {{- end }}
            - name: VGW_HEALTH
              value: "/health"
            {{- if .Values.versitygw.virtualDomain }}
            - name: VGW_VIRTUAL_DOMAIN
              value: {{ .Values.versitygw.virtualDomain }}
            {{- end }}
            {{- if .Values.webui.enabled }}
            - name: VGW_WEBUI_PORT
              value: {{ .Values.webui.port | quote }}
            - name: VGW_WEBUI_NO_TLS
              value: "true"
            - name: VGW_CORS_ALLOW_ORIGIN
              # value: "https://s3explorer.test.slgm.li"
              value: "*"
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "versitygw.fullname" . }}-config
          ports:
            - name: s3
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            {{- if .Values.webui.enabled }}
            - name: webui
              containerPort: {{ .Values.webui.port }}
              protocol: TCP
            {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /mnt/data
              name: data-pvc
          {{- if .Values.persistence.iam.enabled }}
            - mountPath: /mnt/iam
              name: iam-pvc
          {{- end }}
          {{- if .Values.persistence.versioning.enabled }}
            - mountPath: /mnt/versioning
              name: versioning-pvc
          {{- end }}    
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: data-pvc
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-data
      {{- if .Values.persistence.iam.enabled }}
        - name: iam-pvc
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-iam
      {{- end }}
      {{- if .Values.persistence.versioning.enabled }}
        - name: versioning-pvc
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-versioning
      {{- end }}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
